### ISSUE TITLE
Can't play H265 mp4 file

### ISSUE THREAD

**Issue by anhthoai** [strukturag/libde265.js#20]
hello, it can't play H265 mp4 file. Any update to work with that type?

**Comment by fancycode** [comment]
libde265.js is only a bitstream decoder. If you want to decode container files (like `.mp4` is), you will have to extract the actual H265 data yourself or using some other library and pass that data to libde265.js for decoding.

**Comment by youssef-ali** [comment]
> hello, it can't play H265 mp4 file. Any update to work with that type?

Hi Anhthoai, 
I am facing the same problem, did you find a solution?

**Comment by qiangbro** [comment]
遇到同样需求。需要在网页上播放MP4封装的hevc视频，寻求解决方案
