### ISSUE TITLE
IE11 video don't playback

### ISSUE THREAD

**Issue by hodatovich** [strukturag/libde265.js#3]
end line 22 this.Ea=new Worker(ab);
SCRIPT5022: SecurityError

URL-address of at least one BLOB-object revoked by closing BLOB-object for which it was created. Such URL-addresses will not be resolved, as data associated with them have been released.

I tried to set
video.crossOrigin = 'anonymous' 
but it didn’t help.
CORS error?

So, video does not play.

**Comment by fancycode** [comment]
Can you please check with the latest version? I couldn't reproduce this with IE11 now.

**Comment by hodatovich** [comment]
![ie11_265_bug](https://cloud.githubusercontent.com/assets/9132265/8674807/95626e0c-2a59-11e5-86ac-335a29f9d714.jpg)

**Comment by fancycode** [comment]
Hmm ok. I just tested again with IE 11.0.9600.16384 on a freshly installed Windows 8.1 without your problem. Which version are you running? It looks like it can't get the name of the worker function (which is dynamically generated) but uses `undefined` instead.

**Comment by fancycode** [comment]
Added a tentative fix. Could you please try again?

**Comment by hodatovich** [comment]
Yes, now it works!

**Comment by fancycode** [comment]
Great, thanks for reporting/testing!
