### ISSUE TITLE
Live Streaming

### ISSUE THREAD

**Issue by yarontorbaty** [strukturag/libde265.js#5]
Hi,

Is it possible to play live streams using this library?

Thanks,
Yaron T.

**Comment by TomKaltz** [comment]
+1

**Comment by fancycode** [comment]
libde265.js decodes any raw HEVC bitstreams, so you can also feed live streams into the decoder. How to actually do this depends on the source of your stream.

**Comment by fancycode** [comment]
Closing, not really related to libde265.js which doesn't care where the data to decode comes from.
