### ISSUE TITLE
Create Videos

### ISSUE THREAD

**Issue by bitdivine** [strukturag/libde265.js#6]
Hello,

How did you encode the sample hevc file?  I generated a couple of files using [f265](http://f265.org/).  If I bundle these in a matroska file they play happily in your [chrome app](https://chrome.google.com/webstore/detail/h265-hevc-player/dambgipgbnhmnkdolkljibpcbocimnpd?hl=en), however the raw hevc does not play in libde265.js.  Instead I get a hissy screen reminiscent of old analogue TVs when they were out of tune.

I was concerned that perhaps my emscripten build was borked so I downloaded libde265.js and your sample video from your demo site.  I can play your video that way but not my own.

Best wishes, Max

**Comment by bitdivine** [comment]
Update: It looks as if the build used in your online demo is simply out of date.  I rebuilt my own copy using emscripten with all optimisations switched off and my videos played without issue, if a little slowly.  With optimisations switched on I get complaints about "read()" being undefined, but that looks as if it's more of a problem with emscripten than with libde265.  Vielen Dank for a great piece of code!  Now I'll try to get to the bottom of the problem with emscripten.

**Comment by fancycode** [comment]
The libde265.js in the demo should be built using the latest version of libde265 (0.9). Could you please provide a short sample hevc bitstream that shows the error you were getting?

**Comment by fancycode** [comment]
Closing, also the demo has been updated to the latest release.
