### ISSUE TITLE
[enhancement]About the js file size.

### ISSUE THREAD

**Issue by DavidLyu2008** [strukturag/libde265.js#7]
Hi ,

I have download your demo, and run it on local server, it works well.
Great job, Thank you.

But I think this lib is very big, the min file almost 800k, And the js file is creating by Emscripten, it added some additional codes to lib. Do you have other version lib for javascript?

And I want change the video file in demo, it throws an error like issue#2: https://github.com/strukturag/libde265.js/issues/2

Thanks for your working.
David

**Comment by fancycode** [comment]
This is the only version we currently have (i.e. there is no manually-created JS version of libde265). Unfortunately I don't know how to omit certain code when generating using Emscripten, so pull-requests are welcome ;-)

**Comment by DavidLyu2008** [comment]
Thanks @fancycode .

I will migrate it with from libde265 manually When I have time to do it, at that time, please give me some help. :)
But at this time, I have no time.

See you later. haha...
